# server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

# database
POSTGRES_USER: ${POSTGRES_USER}
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
POSTGRES_DB: docdatabase
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432

# email config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ${EMAIL_ID}
EMAIL_PASSWORD: ${EMAIL_PASSWORD}
VERIFY_EMAIL_HOST: http://localhost:8085