# server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

# database
POSTGRES_USER: ${POSTGRES_USER}
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
POSTGRES_DB: docdatabase
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432

# email config
EMAIL_HOST: smpt.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ${EMAIL_ID}
EMAIL_PASSWORD: ${EMAIL_PASSWORD}
VERIFY_EMAIL_HOST: http://securedoc.com

#jwt
JWT_EXPIRATION: 432_000_000 # ms = 5days
JWT_SECRET: ${SECRET}